// ==UserScript==
// @name            UIT - Auto Lecture Survey
// @author          Kevin Nitro
// @namespace       UIT-KevinNitro
// @description     Tự động đánh giá khảo sát giảng viên UIT. vui lòng disable script khi không sử dụng, tránh conflict với các khảo sát / link khác của trường
// @license         https://github.com/KevinNitroG/UIT-Auto-Lecturer-Survey/raw/main/LICENSE
// @version         1.1
// @icon            https://github.com/KevinNitroG/UIT-Auto-Lecturer-Survey/raw/main/UIT-logo.jpg
// @match           http*://survey.uit.edu.vn/index.php/survey/index/sid/*/token/*
// @match           http*://survey.uit.edu.vn/index.php/survey/index
// // @run-at       document-idle
// @downloadURL     https://github.com/KevinNitroG/UIT-Auto-Lecturer-Survey/raw/main/UITAutoLecturerSurvey.user.js
// @updateURL       https://github.com/KevinNitroG/UIT-Auto-Lecturer-Survey/raw/main/UITAutoLecturerSurvey.user.js
// @supportURL      mailto:kevinnitro@duck.com
// ==/UserScript==

// THIS SCRIPT WAS GENERATED BY CHATGPT & My brain for 10% .-.

(function () {
    "use strict";

    // Random sort the array Function
    function sortArrayRandomly(array) {
        return array.sort(function () {
            return Math.random() - 0.5;
        });
    }

    // Find all tag with class "answertext"
    let answerLabels = document.querySelectorAll("label.answertext");
    let firstTypeSelectionsArray = [
        ">80%",
        "50-80%",
        "Từ 70 đến dưới 90%",
        "Trên 90%",
    ];
    // Select first type
    answerLabels.forEach(function (label) {
        while (true) {
            sortArrayRandomly(firstTypeSelectionsArray);
            if (label.innerText.trim() === firstTypeSelectionsArray[0]) {
                label.click();
                break;
            }
        }
    });

    // Trigger onclick on all td tags with class "answer_cell_00MH04 answer-item radio-item"
    // Chọn full các ô thứ 4 trong table đánh giá
    let answerCells = document.querySelectorAll(
        "td.answer_cell_00MH04.answer-item.radio-item"
    );
    answerCells.forEach(function (cell) {
        cell.click();
    });

    // Sleep tí
    setTimeout(function () {}, 100);

    // Check for the button with type="submit" and id="movenextbtn"
    // Ấn tiếp tục
    let moveNextBtn = document.querySelector(
        'button[type="submit"][id="movenextbtn"]'
    );
    if (moveNextBtn) {
        moveNextBtn.click();
    }

    // Trigger onclick on the button with id="movesubmitbtn"
    // Ấn gửi nộp form
    let submitBtn = document.getElementById("movesubmitbtn");
    if (submitBtn) {
        submitBtn.click();
    }
})();
